# Generated by Django 3.2.3 on 2021-06-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=30)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='bebidas',
            new_name='bebida',
        ),
    ]
